import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By {""}
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/desktop" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Desktop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/web" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Web
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/archived" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Archived
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/helpandsupport" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Help and Support
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
